### ISSUE TITLE
Automate syncing with GitHub

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/languages#34]
Currently, after changes are merged into `master`, I need to run a manual step to sync changes to all repositories. 

This could be made faster if we triggered a GitHub action to create PRs instead. 

### Today's workflow

- Merge a PR into `master`
- Clone `languages` locally
- Run `make sync_with_github`, with `GITHUB_TOKEN` as an env var. This'll end up creating pull requests to all repositories.
- Merge PRs (manual) 

### Intended workflow

- Merge a PR into `master`
- A Github Action workflow triggers, which runs `make sync_with_github` and creates pull requests
- Merge PRs (will still be manual)

**Comment by rohitpaulk** [comment]
@syed-ghufran-hassan Since you mentioned that you're interested in the automation aspect, I thought a task related to GitHub actions could be fun to work on 🙂 

Here's what we need to do: 

- Create a new workflow file in this repository named `.github/workflows/sync.yml`
  - Only trigger this on `push` events to the master branch. You can use the [on](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on) keyword to configure this. 
  - Run `make sync_with_github`. 
    - This might need some ruby dependencies, so install these before the command runs.
    - This'll need a `GITHUB_TOKEN` env variable to authenticate with GitHub when creating PRs. Assume that a secret named `GLOBAL_GITHUB_TOKEN` exists with the value to be used.

Here's how I'd approach things: 

- Research
  - Read up about [Github Actions](https://github.com/features/actions)
  - Learn how the [Workflow Syntax](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions) works
  - Learn how to store [secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets) in GitHub actions
- Prototype
  - Create test repositories for yourself. You'll need two repositories to test this - (1) this repository (2) a test repository to sync changes to. 
  - Make changes to code so that your repository is configured to sync changes to your test repository (it syncs to `codecrafters-io/starter-redis-xxx` by default). To understand where this syncing happens, checkout [this file](https://github.com/codecrafters-io/languages/blob/master/repo_syncer/sync.rb). 
  - At this point, the `make sync_with_github` command should run fine for you locally. When there are no changes to be synced it'll do nothing, when there are changes it should create a pull request. 
  - Now you can start implementing the GitHub action and testing things. 
  - Once done, open a PR to this repository. 

Note: You will **NOT** be able to test changes by creating PRs to this repository directly, since it'll need a merge to master to test + you'll need to setup secrets. Test thoroughly on your own test repositories (give me access to them if you'd like any feedback) - and then create a PR once ready. 

As always, open to any questions - happy to help!

**Comment by syed-ghufran-hassan** [comment]
Greetings Sir,

Thank you sir for providing the opportunity. I will definitely look into it
and I will update you also Sir.

Regards,
Syed Ghufran Hassan

**Comment by rohitpaulk** [comment]
Fixed in https://github.com/codecrafters-io/languages/commit/a930471b9bad08146ed51d5ed72b6f33357386e5
