### ISSUE TITLE
Manage redis-starter-php through this repo

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/languages#42]
https://github.com/codecrafters-io/redis-starter-php isn't wired up to this repo - looks like we didn't include it when creating this repo. 

A bit of context: earlier we maintained repositories individually, and not through a central repository. We only had 2-3 languages at the time, so it was easier to do. As the number of languages grew it became harder to ensure consistency across all repositories, so we created this repo and the templating logic to ensure consistency. 

Thanks to @FastestCoderOnEarth for pointing this out!

**Comment by FastestCoderOnEarth** [comment]
@rohitpaulk This is fixed in this PR, https://github.com/codecrafters-io/languages/pull/45

**Comment by rohitpaulk** [comment]
Fixed by @FastestCoderOnEarth in https://github.com/codecrafters-io/languages/pull/45
